name: Crave Build

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Project name of foss.crave.io
        type: choice
        default: PixelOS
        options:
          - PixelOS
          - DerpFest
          - LineageOS
          - AOSP
          - TWRP
      device_code:
        description: Device code
        required: true
      build_variant:
        description: Build variant
        type: choice
        default: userdebug
        options:
          - eng
          - userdebug
          - user
      local_manifests:
        description: Local manifests
        required: false
      clean_build:
        description: Clean build
        type: boolean
        default: false

jobs:
  build:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.repository_owner }}
    env:
      TZ: Asia/Taipei
    steps:
      - name: Setup environment variables
        run: |
          case "${{ inputs.project_name }}" in
            PixelOS)
              PROJECT_ID=82
              ;;
            DerpFest)
              PROJECT_ID=64
              ;;
            LineageOS-22.1)
              PROJECT_ID=93
              ;;
            AOSP)
              PROJECT_ID=35
              ;;
            TWRP)
              PROJECT_ID=78
              ;;
            *)
              echo "unknown project_name."
              exit 1
              ;;
          esac

          if [ "${{ inputs.clean_build }}" = true ]; then
            CLEAN_BUILD=1
          else
            CLEAN_BUILD=0
          fi

          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
          echo "PROJECT_DIR=/crave-devspaces/${{ inputs.project_name }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=${{ inputs.project_name }}" >> $GITHUB_ENV
          echo "DEVICE_CODE=${{ inputs.device_code }}" >> $GITHUB_ENV
          echo "BUILD_VARIANT=${{ inputs.build_variant }}" >> $GITHUB_ENV
          echo "LOCAL_MANIFESTS=${{ inputs.local_manifests }}" >> $GITHUB_ENV
          echo "CLEAN_BUILD=$CLEAN_BUILD" >> $GITHUB_ENV

          # remove extra double quotes, god knows why there are two extra double quotes
          DCMASTER=${DCMASTER//\"/}
          echo "DCMASTER=$DCMASTER" >> $GITHUB_ENV

      - name: Setup project
        run: |
          if grep -q "$PROJECT_ID" <(crave clone list --json | jq -r '.clones[]."Project ID"'); then
            crave clone destroy -y $PROJECT_DIR || {
              echo "Project \"$PROJECT_NAME\" destroy failed."
              exit 1
            }
          fi
          crave clone create --projectID $PROJECT_ID $PROJECT_DIR || {
            echo "Project \"$PROJECT_NAME\" create failed."
            exit 1
          }

      - name: Start build queue
        timeout-minutes: 720
        run: |
          [ "$CLEAN_BUILD" = 0 ] || CRAVE_RUN_ARGS="$CRAVE_RUN_ARGS --clean"
          cd $PROJECT_DIR
          crave run --no-patch $CRAVE_RUN_ARGS -- '
            curl -sSL https://raw.githubusercontent.com/pexcn/android-rom-builder/refs/heads/master/build.sh | bash -s -- \
              --device $DEVICE_CODE \
              --variant $BUILD_VARIANT \
              --manifest $LOCAL_MANIFESTS \
              --reset
          '
