name: Create self-hosted runner

on:
  workflow_dispatch:
    inputs:
      RUNNER_TOKEN:
        description: 'GitHub actions self-hosted runner token.'
        required: true

jobs:
  create-runner:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Taipei
      CRAVE_USERNAME: ${{ secrets.CRAVE_USERNAME }}
      CRAVE_TOKEN: ${{ secrets.CRAVE_TOKEN }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install crave
        run: |
          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash
          mv crave /usr/local/bin
          envsubst < crave.conf.sample > crave.conf

      - name: Configure runner
        run: |
          crave devspace -- '
            version=$(curl -sSL https://api.github.com/repos/actions/runner/releases/latest | jq -r .tag_name | sed 's/v//')
            rm -rf actions-runner && mkdir actions-runner
            curl -L https://github.com/actions/runner/releases/download/v${version}/actions-runner-linux-x64-${version}.tar.gz | \
              tar -zxf - -C actions-runner
            cd actions-runner
            ./config.sh --unattended --replace --name crave --url "https://github.com/${{ github.repository }}" --token "${{ inputs.RUNNER_TOKEN }}"
          '

      - name: Connect runner
        run: |
          crave devspace -- 'cd actions-runner && ./run.sh' &
          sleep 30
